/**
 * Created by yangyang on 2017/6/30.
 */

export const INPUTFORM_INITIALIZED = 'INPUTFORM_INITIALIZED'
export const INPUTFORM_INIT_STATE = "INPUTFORM_INIT_STATE"
export const INPUTFORM_CHANGING = 'INPUTFORM_CHANGING'
export const INPUTFORM_ON_CHANGE = "INPUTFORM_ON_CHANGE"
export const INPUTFORM_DESTROYED = 'INPUTFORM_DESTROYED'
export const INPUTFORM_DESTROY = "INPUTFORM_DESTROY"
export const INPUTFORM_CHECKING = 'INPUTFORM_CHECKING'
export const INPUTFORM_VALID_CHECK = "INPUTFORM_VALID_CHECK"